version: '3'
services:
    php:
        build:
          context: .
        volumes:
            - ./:/var/www/symfony:cached
            - ./var:/var/www/symfony/var:cached
        links:
            - db

    web:
        build:
          context: .
          dockerfile: ./Dockerfile.nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/symfony:cached
            - ./var:/var/www/symfony/var:cached
        links:
            - php
    db:
        image: mysql:5.7
        volumes:
            - "./docker/.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: secret


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db